        [package]
        name = "ep-app-ledger"
        edition.workspace = true
        version.workspace = true
        publish.workspace = true

        [lints]
        workspace = true

        [dependencies]
        ep-foundation.workspace = true
ep-contract-ledger.workspace = true
ep-domain-ledger.workspace = true
